// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForBulkCreateUsers implements pgx.CopyFromSource.
type iteratorForBulkCreateUsers struct {
	rows                 []BulkCreateUsersParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkCreateUsers) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkCreateUsers) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].FullName,
		r.rows[0].Email,
		r.rows[0].Password,
	}, nil
}

func (r iteratorForBulkCreateUsers) Err() error {
	return nil
}

func (q *Queries) BulkCreateUsers(ctx context.Context, arg []BulkCreateUsersParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"users"}, []string{"id", "full_name", "email", "password"}, &iteratorForBulkCreateUsers{rows: arg})
}
