// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	BulkCreateUsers(ctx context.Context, arg []BulkCreateUsersParams) (int64, error)
	CheckRefreshToken(ctx context.Context, jti string) (bool, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (string, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	RevokeRefreshToken(ctx context.Context, jti string) error
	SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) error
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
}

var _ Querier = (*Queries)(nil)
