// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type BulkCreateUsersParams struct {
	ID       string      `json:"id"`
	FullName pgtype.Text `json:"full_name"`
	Email    string      `json:"email"`
	Password []byte      `json:"password"`
}

const checkRefreshToken = `-- name: CheckRefreshToken :one
SELECT EXISTS(
    SELECT 1 FROM refresh_tokens WHERE jti = $1
)
`

func (q *Queries) CheckRefreshToken(ctx context.Context, jti string) (bool, error) {
	row := q.db.QueryRow(ctx, checkRefreshToken, jti)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, full_name, email, password)
VALUES (gen_random_uuid(), $1, $2, $3)
RETURNING id
`

type CreateUserParams struct {
	FullName pgtype.Text `json:"full_name"`
	Email    string      `json:"email"`
	Password []byte      `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (string, error) {
	row := q.db.QueryRow(ctx, createUser, arg.FullName, arg.Email, arg.Password)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, full_name, email, password
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID       string      `json:"id"`
	FullName pgtype.Text `json:"full_name"`
	Email    string      `json:"email"`
	Password []byte      `json:"password"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, full_name, email, password
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID       string      `json:"id"`
	FullName pgtype.Text `json:"full_name"`
	Email    string      `json:"email"`
	Password []byte      `json:"password"`
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
DELETE FROM refresh_tokens
WHERE jti = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, jti string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, jti)
	return err
}

const saveRefreshToken = `-- name: SaveRefreshToken :exec
INSERT INTO refresh_tokens (jti, user_id, expires_at)
VALUES ($1, $2, $3)
`

type SaveRefreshTokenParams struct {
	Jti       string    `json:"jti"`
	UserID    string    `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) SaveRefreshToken(ctx context.Context, arg SaveRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, saveRefreshToken, arg.Jti, arg.UserID, arg.ExpiresAt)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET password = $1
WHERE id = $2
`

type UpdatePasswordParams struct {
	Password []byte `json:"password"`
	ID       string `json:"id"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.Password, arg.ID)
	return err
}
